openapi: 3.0.3
info:
  title: Task Manager API
  description: API para gestionar tareas con autenticación de usuarios
  version: 1.0.0
  contact:
    email: tu_email@ejemplo.com
servers:
  - url: 'http://localhost:3000'
    description: Servidor local de desarrollo
tags:
  - name: Usuarios
    description: Operaciones relacionadas con usuarios
  - name: Tareas
    description: Operaciones relacionadas con tareas
  - name: Categorías
    description: Operaciones relacionadas con categorías

paths:
  /api/users/register:
    post:
      tags:
        - Usuarios
      operationId: registerUser
      summary: Registrar un nuevo usuario
      description: Crea un nuevo usuario en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuario registrado
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Datos inválidos o usuario ya existente
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - type: object
                    properties:
                      message:
                        type: string
                        example: Usuario ya registrado
        '500':
          $ref: '#/components/responses/ServerError'

  /api/users/login:
    post:
      tags:
        - Usuarios
      operationId: loginUser
      summary: Iniciar sesión
      description: Autentica a un usuario y devuelve un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login exitoso
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '400':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - type: object
                    properties:
                      message:
                        type: string
                        example: Usuario no encontrado
        '500':
          $ref: '#/components/responses/ServerError'

  /api/tasks:
    post:
      tags:
        - Tareas
      operationId: createTask
      summary: Crear una nueva tarea
      description: Crea una nueva tarea asociada al usuario autenticado
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Tarea creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
          
    get:
      tags:
        - Tareas
      operationId: getTasks
      summary: Obtener todas las tareas
      description: Obtiene todas las tareas del usuario autenticado
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/tasks/{id}:
    get:
      tags:
        - Tareas
      operationId: getTaskById
      summary: Obtener tarea por ID
      description: Obtiene una tarea específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea
      responses:
        '200':
          description: Tarea encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Tarea no encontrada
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      tags:
        - Tareas
      operationId: updateTask
      summary: Actualizar tarea
      description: Actualiza una tarea específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Tarea actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Tarea no encontrada
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Tareas
      operationId: deleteTask
      summary: Eliminar tarea
      description: Elimina una tarea específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea
      responses:
        '200':
          description: Tarea eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tarea eliminada correctamente
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Tarea no encontrada
        '500':
          $ref: '#/components/responses/ServerError'

  /api/categories:
    post:
      tags:
        - Categorías
      operationId: createCategory
      summary: Crear una nueva categoría
      description: Crea una nueva categoría asociada al usuario autenticado
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        '201':
          description: Categoría creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - type: object
                    properties:
                      error:
                        type: string
                        example: El nombre de la categoría es obligatorio
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
    get:
      tags:
        - Categorías
      operationId: getCategories
      summary: Obtener todas las categorías
      description: Obtiene todas las categorías del usuario autenticado
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/categories/{id}:
    get:
      tags:
        - Categorías
      operationId: getCategoryById
      summary: Obtener categoría por ID
      description: Obtiene una categoría específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la categoría
      responses:
        '200':
          description: Categoría encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryWithTasks'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Categoría no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Categoría no encontrada
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - Categorías
      operationId: updateCategory
      summary: Actualizar categoría
      description: Actualiza una categoría específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        '200':
          description: Categoría actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Categoría no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Categoría no encontrada
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - Categorías
      operationId: deleteCategory
      summary: Eliminar categoría
      description: Elimina una categoría específica del usuario autenticado
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la categoría
      responses:
        '200':
          description: Categoría eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Categoría eliminada correctamente
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Categoría no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Categoría no encontrada
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    UserRegistration:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: usuario@example.com
        password:
          type: string
          format: password
          minLength: 6
          example: contraseña123
          
    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: usuario@example.com
        password:
          type: string
          format: password
          example: contraseña123
          
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          format: email
          example: usuario@example.com
        createdAt:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
          
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Completar informe
        description:
          type: string
          example: Terminar el informe trimestral para la reunión del lunes
        categoryId:
          type: integer
          example: 2
          nullable: true
          
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          example: Completar informe
        description:
          type: string
          example: Terminar el informe trimestral para la reunión del martes
        completed:
          type: boolean
          example: true
        categoryId:
          type: integer
          example: 2
          nullable: true
          
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Completar informe
        description:
          type: string
          example: Terminar el informe trimestral para la reunión del lunes
        completed:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
        userId:
          type: integer
          example: 1
          
    CategoryCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Trabajo
        color:
          type: string
          example: '#FF0000'
          
    CategoryUpdate:
      type: object
      properties:
        name:
          type: string
          example: Personal
        color:
          type: string
          example: '#00FF00'
          
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Trabajo
        color:
          type: string
          example: '#FF0000'
        createdAt:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
        userId:
          type: integer
          example: 1
          
    CategoryWithTasks:
      allOf:
        - $ref: '#/components/schemas/Category'
        - type: object
          properties:
            tasks:
              type: array
              items:
                $ref: '#/components/schemas/Task'
                
    ValidationError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              msg:
                type: string
                example: Debe ser un email válido
              param:
                type: string
                example: email
              location:
                type: string
                example: body
  
  responses:
    Unauthorized:
      description: No autorizado - token no proporcionado
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: No token provided
    
    Forbidden:
      description: Prohibido - token inválido o expirado
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Token inválido

    ServerError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Error interno del servidor
